site_name: Lunaar Docs
site_description: "Lunaar Documentation"

theme:
  name: material
  logo: "https://lunaar.org/media/logo.svg"
  favicon: "https://lunaar.org/media/logo.svg"
  palette:
    # Auto mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  font:
    text: Poppins
    code: Roboto Mono
  features:
    - navigation.expand
    - navigation.sections
    - navigation.top
    - content.code.annotate # for code highlighting annotations

markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
      use_pygments: true
  - pymdownx.superfences
  - toc:
      permalink: true

plugins:
  - search
